server:
  port: 8081

spring:
  application:
    name: book-client

  datasource:
    url: jdbc:postgresql://localhost:5432/books
    username: lera
    password: lera
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka